# Generated by Django 5.1.4 on 2025-01-15 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HGcity', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('like', 'Лайк'), ('dislike', 'Дизлайк')], max_length=10)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HGcity.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'message')},
            },
        ),
    ]
