# Generated by Django 5.1.4 on 2025-01-15 14:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HGcity', '0004_remove_message_dislikes_remove_message_flagged_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='message',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='reported',
            field=models.ManyToManyField(blank=True, related_name='reported_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='LikeDislike',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
