# Generated by Django 5.1.4 on 2025-01-15 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HGcity', '0006_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Жалоба', 'verbose_name_plural': 'Жалобы'},
        ),
    ]
