# Generated by Django 5.1.4 on 2025-01-15 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HGcity', '0007_alter_report_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='message',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
