# Generated by Django 5.1.4 on 2025-01-16 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HGcity', '0010_alter_chatmessage_options_alter_complaint_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='message',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
