# Generated by Django 5.1.4 on 2025-01-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HGcity', '0012_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Resident', 'Житель'), ('Moderator', 'ГОХ'), ('Government', 'Правительство')], default='Житель', max_length=20),
        ),
    ]
