# Generated by Django 5.1.4 on 2025-01-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HGcity', '0013_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Житель', 'Resident'), ('ГОХ', 'Moderator'), ('Правительство', 'Government')], default='Житель', max_length=20),
        ),
    ]
