# Generated by Django 5.1.4 on 2025-01-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HGcity', '0015_user_is_banned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
