# Generated by Django 5.1.4 on 2025-01-16 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HGcity', '0018_alter_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
