# Generated by Django 5.1.4 on 2025-01-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HGcity', '0020_message_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
