# Generated by Django 5.1.4 on 2025-01-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HGcity', '0023_user_is_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ideology',
            field=models.CharField(blank=True, choices=[('Национализм', 'Национализм'), ('Социализм', 'Социализм'), ('Демократия', 'Демократия'), ('Монархизм', 'Монархизм')], default='None', max_length=20, null=True),
        ),
    ]
