# Generated by Django 5.1.4 on 2025-01-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HGcity', '0024_alter_user_ideology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Житель', 'Житель'), ('ГОХ', 'ГОХ'), ('Правительство', 'Правительство')], default='Житель', max_length=20),
        ),
    ]
