# Generated by Django 5.1.4 on 2025-01-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HGcity', '0025_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='Без Имени', max_length=100, null=True, verbose_name='Имя персонажа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hp',
            field=models.IntegerField(blank=True, default=100, null=True, verbose_name='Жизни'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ideology',
            field=models.CharField(blank=True, choices=[('Национализм', 'Национализм'), ('Социализм', 'Социализм'), ('Демократия', 'Демократия'), ('Монархизм', 'Монархизм')], default='None', max_length=20, null=True, verbose_name='Идеология'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='Бан'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='Подтверждение почты'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='Без Фамилии', max_length=100, null=True, verbose_name='Фамилия персонажа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения имени'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_username_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения лого'),
        ),
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Лого'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Житель', 'Житель'), ('ГОХ', 'ГОХ'), ('Правительство', 'Правительство')], default='Житель', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='social_rating',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Соц.рейтинг'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Кошелек'),
        ),
    ]
