# Generated by Django 5.1.4 on 2025-01-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HGcity', '0028_alter_user_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Лого'),
        ),
    ]
