# Generated by Django 5.1.4 on 2025-01-22 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HGcity', '0030_alter_user_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banneded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Причина')),
                ('banned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата бана')),
                ('banned_by_username', models.CharField(max_length=255, verbose_name='Бан от')),
                ('banned_by_role', models.CharField(max_length=255, verbose_name='Бан от Роли')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ban_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
