# Generated by Django 5.1.4 on 2025-01-22 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HGcity', '0031_banneded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banneded',
            options={'verbose_name': 'Бан', 'verbose_name_plural': 'Баны'},
        ),
    ]
