# Generated by Django 5.1.4 on 2025-01-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HGcity', '0033_alter_user_chat_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.TextField(blank=True, default='Здесь может быть ваша биография...', max_length=1000, null=True, verbose_name='Биография'),
        ),
    ]
