# Generated by Django 5.1.4 on 2025-01-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HGcity', '0036_alter_user_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Житель', 'Житель'), ('ГОХ', 'ГОХ'), ('Капитан Гох', 'Капитан Гох'), ('Правительство', 'Правительство')], default='Житель', max_length=20, verbose_name='Роль'),
        ),
    ]
