# Generated by Django 5.1.4 on 2025-01-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HGcity', '0039_remove_user_mute_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='biography',
            field=models.TextField(default='Здесь может быть ваша биография...', max_length=1000, null=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Житель', 'Житель'), ('ГОХ', 'ГОХ'), ('Капитан Гох', 'Капитан Гох'), ('Система', 'Система')], default='Житель', max_length=20, verbose_name='Роль'),
        ),
    ]
