# Generated by Django 5.1.4 on 2025-01-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HGcity', '0040_alter_user_biography_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin_code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Пин код'),
        ),
    ]
