# Generated by Django 5.1.4 on 2025-01-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HGcity', '0041_user_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='Имя', max_length=100, null=True, verbose_name='Имя персонажа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='Фамилия', max_length=100, null=True, verbose_name='Фамилия персонажа'),
        ),
    ]
