# Generated by Django 5.1.4 on 2025-02-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HGcity', '0042_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='biography',
            field=models.TextField(default='Здесь может быть ваша биография...', max_length=3000, null=True, verbose_name='Биография'),
        ),
    ]
