# Generated by Django 5.1.4 on 2025-02-04 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HGcity', '0043_user_registration_ip_alter_user_biography'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название работы')),
                ('max_workers', models.IntegerField(default=0, verbose_name='Максимальное количество работников')),
                ('current_workers', models.ManyToManyField(blank=True, related_name='jobs', to=settings.AUTH_USER_MODEL, verbose_name='Работники')),
            ],
        ),
    ]
