# Generated by Django 5.1.4 on 2025-02-04 08:51

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HGcity', '0044_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание работы'),
        ),
        migrations.AlterField(
            model_name='job',
            name='current_workers',
            field=models.ManyToManyField(blank=True, related_name='jobs', to=settings.AUTH_USER_MODEL, verbose_name='Текущие работники'),
        ),
        migrations.AlterField(
            model_name='job',
            name='max_workers',
            field=models.PositiveIntegerField(verbose_name='Максимальное количество работников'),
        ),
    ]
