# Generated by Django 5.1.4 on 2025-02-04 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HGcity', '0045_job_created_at_job_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
