# Generated by Django 5.1.4 on 2025-02-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HGcity', '0046_delete_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='biography',
            field=models.TextField(default='Здесь может быть ваша биография...', max_length=5000, null=True, verbose_name='Биография'),
        ),
    ]
