# Generated by Django 5.1.4 on 2025-02-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HGcity', '0049_message_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='visit_history',
            field=models.JSONField(default=list, verbose_name='Последний вход'),
        ),
    ]
