# Generated by Django 5.1.4 on 2025-02-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HGcity', '0050_user_visit_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='visit_history',
            field=models.JSONField(default=list, null=True, verbose_name='Последний вход'),
        ),
    ]
