# Generated by Django 5.1.4 on 2025-02-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HGcity', '0052_alter_user_visit_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='visit_history',
        ),
        migrations.AddField(
            model_name='user',
            name='clicks_today',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Клики за день'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_entry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний вход'),
        ),
    ]
