# Generated by Django 5.1.4 on 2025-02-13 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HGcity', '0053_remove_user_visit_history_user_clicks_today_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='clicks_today',
        ),
    ]
