# Generated by Django 5.1.4 on 2025-02-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HGcity', '0054_remove_user_clicks_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='factory_visits',
            field=models.IntegerField(default=0, verbose_name='Количество входов в фабрику'),
        ),
    ]
